<a href="https://colab.research.google.com/github/alishaminj12/alisha_data690/blob/main/assignment_05/NumPy/NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Assignment 05
- Name - Alisha Minj
- Date - 03-05-2022

## Numpy

In [146]:
import sys
import numpy as np

## Basic Numpy Arrays

In [147]:
np.array([1, 2, 3, 4])

array([1, 2, 3, 4])

In [148]:
a = np.array([1, 2, 3, 4])

In [149]:
b = np.array([0, .5, 1, 1.5, 2])

In [150]:
a[0], a[1]

(1, 2)

In [151]:
a[0:]

array([1, 2, 3, 4])

In [152]:
a[1:3]

array([2, 3])

In [153]:
a[1:-1]

array([2, 3])

In [154]:
a[::2]

array([1, 3])

In [155]:
b

array([0. , 0.5, 1. , 1.5, 2. ])

In [156]:
b[0], b[2], b[-1]

(0.0, 1.0, 2.0)

In [157]:
b[[0, 2, -1]]

array([0., 1., 2.])

## Array Types

In [158]:
a

array([1, 2, 3, 4])

In [159]:
a.dtype

dtype('int64')

In [160]:
b

array([0. , 0.5, 1. , 1.5, 2. ])

In [161]:
b.dtype

dtype('float64')

In [162]:
np.array([1, 2, 3, 4], dtype=np.float)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  """Entry point for launching an IPython kernel.


array([1., 2., 3., 4.])

In [163]:
np.array([1, 2, 3, 4], dtype=np.int8)

array([1, 2, 3, 4], dtype=int8)

In [164]:
c = np.array(['a', 'b', 'c'])

In [165]:
c.dtype

dtype('<U1')

In [166]:
d = np.array([{'a': 1}, sys])

In [167]:
d.dtype

dtype('O')

## Dimensions and shapes

In [168]:
A = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

In [169]:
A.shape

(2, 3)

In [170]:
A.ndim

2

In [171]:
A.size

6

In [172]:
B = np.array([
    [
        [12, 11, 10],
        [9, 8, 7],
    ],
    [
        [6, 5, 4],
        [3, 2, 1]
    ]
])

In [173]:
B

array([[[12, 11, 10],
        [ 9,  8,  7]],

       [[ 6,  5,  4],
        [ 3,  2,  1]]])

In [174]:
B.shape

(2, 2, 3)

In [175]:
B.ndim

3

In [176]:
B.size

12

In [177]:
C = np.array([
    [
        [12, 11, 10],
        [9, 8, 7],
    ],
    [
        [6, 5, 4]
    ]
])

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:7: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  import sys


In [178]:
C.dtype

dtype('O')

In [179]:
C.shape

(2,)

In [180]:
C.size

2

In [181]:
type(C[0])

list

## Indexing and Slicing of Matrices

In [182]:
# Square matrix
A = np.array([
#.   0. 1. 2
    [1, 2, 3], # 0
    [4, 5, 6], # 1
    [7, 8, 9]  # 2
])

In [183]:
A[1]

array([4, 5, 6])

In [184]:
A[1][0]

4

In [185]:
# A[d1, d2, d3, d4]

In [186]:
A[1, 0]

4

In [187]:
A[0:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [188]:
A[:, :2]

array([[1, 2],
       [4, 5],
       [7, 8]])

In [189]:
A[:2, :2]

array([[1, 2],
       [4, 5]])

In [190]:
A[:2, 2:]

array([[3],
       [6]])

In [191]:
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [192]:
A[1] = np.array([10, 10, 10])

In [193]:
A

array([[ 1,  2,  3],
       [10, 10, 10],
       [ 7,  8,  9]])

In [194]:
A[2] = 99

In [195]:
A

array([[ 1,  2,  3],
       [10, 10, 10],
       [99, 99, 99]])

## Summary statistics

In [196]:
a = np.array([1, 2, 3, 4])

In [197]:
a.sum()

10

In [198]:
a.mean()

2.5

In [199]:
a.std()

1.118033988749895

In [200]:
a.var()

1.25

In [201]:
A = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

In [202]:
A.sum()

45

In [203]:
A.mean()

5.0

In [204]:
A.std()

2.581988897471611

In [205]:
A.sum(axis=0)

array([12, 15, 18])

In [206]:
A.sum(axis=1)

array([ 6, 15, 24])

In [207]:
A.mean(axis=0)

array([4., 5., 6.])

In [208]:
A.mean(axis=1)

array([2., 5., 8.])

In [209]:
A.std(axis=0)

array([2.44948974, 2.44948974, 2.44948974])

In [210]:
A.std(axis=1)

array([0.81649658, 0.81649658, 0.81649658])

## Broadcasting and Vectorized operations

In [211]:
a = np.arange(4)

In [212]:
a

array([0, 1, 2, 3])

In [213]:
a + 10

array([10, 11, 12, 13])

In [214]:
a * 10

array([ 0, 10, 20, 30])

In [215]:
a

array([0, 1, 2, 3])

In [216]:
a += 100

In [217]:
a

array([100, 101, 102, 103])

In [218]:
l = [0, 1, 2, 3]

In [219]:
[i * 10 for i in l]

[0, 10, 20, 30]

In [220]:
a = np.arange(4)

In [221]:
a

array([0, 1, 2, 3])

In [222]:
b = np.array([10, 10, 10, 10])

In [223]:
b

array([10, 10, 10, 10])

In [224]:
a + b

array([10, 11, 12, 13])

In [225]:
a * b

array([ 0, 10, 20, 30])

## Boolean arrays


In [226]:
a = np.arange(4)

In [227]:
a

array([0, 1, 2, 3])

In [228]:
a[0], a[-1]

(0, 3)

In [229]:
a[[0, -1]]

array([0, 3])

In [230]:
a[[True, False, False, True]]

array([0, 3])

In [231]:
a

array([0, 1, 2, 3])

In [232]:
a >= 2

array([False, False,  True,  True])

In [233]:
a[a >= 2]

array([2, 3])

In [234]:
a.mean()

1.5

In [235]:
a[a > a.mean()]

array([2, 3])

In [236]:
a[~(a > a.mean())]

array([0, 1])

In [237]:
a[(a == 0) | (a == 1)]

array([0, 1])

In [238]:
a[(a <= 2) & (a % 2 == 0)]

array([0, 2])

In [239]:
A = np.random.randint(100, size=(3, 3))

In [240]:
A

array([[10, 31, 89],
       [36, 64, 80],
       [18, 42, 74]])

In [241]:
A[np.array([
    [True, False, True],
    [False, True, False],
    [True, False, True]
])]

array([10, 89, 64, 18, 74])

In [242]:
A > 30

array([[False,  True,  True],
       [ True,  True,  True],
       [False,  True,  True]])

In [243]:
A[A > 30]

array([31, 89, 36, 64, 80, 42, 74])

## Linear Algebra

In [244]:
A = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

In [245]:
B = np.array([
    [6, 5],
    [4, 3],
    [2, 1]
])

In [246]:
A.dot(B)

array([[20, 14],
       [56, 41],
       [92, 68]])

In [247]:
A @ B

array([[20, 14],
       [56, 41],
       [92, 68]])

In [248]:
B.T

array([[6, 4, 2],
       [5, 3, 1]])

In [249]:
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [250]:
B.T @ A

array([[36, 48, 60],
       [24, 33, 42]])

## Size of objects in Memory

### Int, floats

In [251]:
# An integer in Python is > 24bytes
sys.getsizeof(1)

28

In [252]:
# Longs are even larger
sys.getsizeof(10**100)

72

In [253]:
# Numpy size is much smaller
np.dtype(int).itemsize

8

In [254]:
# Numpy size is much smaller
np.dtype(np.int8).itemsize

1

In [255]:
np.dtype(float).itemsize

8

### Lists are even larger

In [256]:
# A one-element list
sys.getsizeof([1])

80

In [257]:
# An array of one element in numpy
np.array([1]).nbytes

8

### And performance is also important

In [258]:
l = list(range(100000))

In [259]:
a = np.arange(100000)

In [260]:
%time np.sum(a ** 2)

CPU times: user 468 µs, sys: 62 µs, total: 530 µs
Wall time: 540 µs


333328333350000

In [261]:
%time sum([x ** 2 for x in l])

CPU times: user 47.3 ms, sys: 3.43 ms, total: 50.7 ms
Wall time: 75.1 ms


333328333350000

## Useful Numpy functions

random

In [262]:
np.random.random(size=2)

array([0.45214944, 0.34144105])

In [263]:
np.random.normal(size=2)

array([ 0.4376959 , -1.15033028])

In [264]:
np.random.rand(2, 4)

array([[0.87108645, 0.43969446, 0.09744109, 0.9182141 ],
       [0.35593273, 0.31186262, 0.70905311, 0.61953243]])

### arange

In [265]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [266]:
np.arange(5, 10)

array([5, 6, 7, 8, 9])

In [267]:
np.arange(0, 1, .1)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9])

### reshape

In [268]:
np.arange(10).reshape(2, 5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [269]:
np.arange(10).reshape(5, 2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

### linspace

In [270]:
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [271]:
np.linspace(0, 1, 20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

In [272]:
np.linspace(0, 1, 20, False)

array([0.  , 0.05, 0.1 , 0.15, 0.2 , 0.25, 0.3 , 0.35, 0.4 , 0.45, 0.5 ,
       0.55, 0.6 , 0.65, 0.7 , 0.75, 0.8 , 0.85, 0.9 , 0.95])

### zeros, ones, empty

In [273]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [274]:
np.zeros((3, 3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [275]:
np.zeros((3, 3), dtype=np.int)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  """Entry point for launching an IPython kernel.


array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [276]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [277]:
np.ones((3, 3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [278]:
np.empty(5)

array([1., 1., 1., 1., 1.])

In [279]:
np.empty((2, 2))

array([[0.25, 0.5 ],
       [0.75, 1.  ]])

### identity and eye

In [280]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [281]:
np.eye(3, 3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [282]:
np.eye(8, 4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [283]:
np.eye(8, 4, k=1)

array([[0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [284]:
np.eye(8, 4, k=-3)

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.]])

In [285]:
"Hello World"[6]

'W'