<a href="https://colab.research.google.com/github/alishaminj12/alisha_data690/blob/main/assignment_05/Data%20Cleaning/Missing_Data.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Assignment 05
- Name - Alisha Minj
- Date - 03-05-2022

##Missing Data

In [1]:
import numpy as np
import pandas as pd

In [2]:
falsy_values = (0, False, None, '', [], {})

In [3]:
any(falsy_values)

False

In [4]:
#NaN: "Not a number"
np.nan

nan

In [5]:
3 + np.nan

nan

In [6]:
a = np.array([1, 2, 3, np.nan, np.nan, 4])

In [7]:
a.sum()

nan

In [8]:
a.mean()

nan

In [49]:
#3 + None

In [27]:
a = np.array([1, 2, 3, np.nan, None, 4], dtype='float')

In [28]:
a

array([ 1.,  2.,  3., nan, nan,  4.])

In [29]:
a = np.array([1, 2, 3, np.nan, np.nan, 4])

In [30]:
a.mean()

nan

In [31]:
a.sum()

nan

In [32]:
np.inf

inf

In [33]:
3 + np.inf

inf

In [34]:
np.inf / 3

inf

In [35]:
np.inf / np.inf

nan

In [36]:
b = np.array([1, 2, 3, np.inf, np.nan, 4], dtype=np.float)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  """Entry point for launching an IPython kernel.


In [37]:
b.sum()

nan



### Checking for `nan` or `inf`


In [38]:
np.isnan(np.nan)

True

In [39]:
np.isinf(np.inf)

True

In [40]:
np.isfinite(np.nan), np.isfinite(np.inf)

(False, False)

In [41]:
np.isnan(np.array([1, 2, 3, np.nan, np.inf, 4]))

array([False, False, False,  True, False, False])

In [42]:
np.isinf(np.array([1, 2, 3, np.nan, np.inf, 4]))

array([False, False, False, False,  True, False])

In [43]:
np.isfinite(np.array([1, 2, 3, np.nan, np.inf, 4]))

array([ True,  True,  True, False, False,  True])



### Filtering them out



In [44]:
a = np.array([1, 2, 3, np.nan, np.nan, 4])

In [45]:
a[~np.isnan(a)]

array([1., 2., 3., 4.])

In [46]:
a[np.isfinite(a)]

array([1., 2., 3., 4.])

In [47]:
a[np.isfinite(a)].sum()

10.0

In [48]:
a[np.isfinite(a)].mean()

2.5